# Simpleapp NodePort Service
---
apiVersion: v1
kind: Service
metadata:
  name: simpleappui
spec:
  selector:
    name: simpleappui
    app: simpleappui-app
  type: NodePort
  ports:
  - nodePort: 32000
    port: 3000
    targetPort: 3000
---
#  Simpleapp Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleappui-deploy
spec:
  selector:
    matchLabels:
      app: simpleappui-app
  replicas: 1
  template:
    metadata:
      name: simpleappui
      labels:
        app: simpleappui-app
    spec:
      containers:
        - name: simpleappui
          image: bathurudocker/simpleappui:1.0.0
          ports:
            - containerPort: 3000
# Simpleapp ClusterIP Service
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapprest
spec:
  selector:
    app: simpleapprest-app
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
#  Simpleapp Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapprest-deploy
spec:
  selector:
    matchLabels:
      app: simpleapprest-app
  replicas: 1
  template:
    metadata:
      name: simpleapprest
      labels:
        app: simpleapprest-app
    spec:
      containers:
        - name: simpleapprest
          image: bathurudocker/simpleapprest:latest
          ports:
            - containerPort: 8080
